Example 1 - Build a Python environment with all dependencies installed, ready to run app.py.
FROM python:3.11-slim					# Start from a base image
WORKDIR /app						# Set working directory
COPY requirements.txt .					# Copy requirements file
RUN pip install --no-cache-dir -r requirements.txt	# Install dependencies
COPY . .							# Copy project files
EXPOSE 5000
CMD ["python", "app.py"]				# Run the application

Example 2 – Build a java environment
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY homepage-0.0.1-SNAPSHOT.jar .
EXPOSE 8080
CMD ["java", "-jar", "homepage-0.0.1-SNAPSHOT.jar"]
